//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cita
    {
        public int codigoCita { get; set; }
        public string nombreCita { get; set; }
        public Nullable<System.DateTime> fechaCita { get; set; }
        public Nullable<System.TimeSpan> horaInicio { get; set; }
        public Nullable<System.TimeSpan> horaFin { get; set; }
        public Nullable<int> fk_codigoVeterinario { get; set; }
        public Nullable<int> fk_codigoAnimal { get; set; }
    
        public virtual Animal Animal { get; set; }
        public virtual veterinario veterinario { get; set; }
    }
}
